**Basic Python**

**1. Split this string**

In [3]:
s = "Hi there Sam!"

In [4]:
print(s.split())

['Hi', 'there', 'Sam!']


**2. Use .format() to print the following string.**

**Output should be: The diameter of Earth is 12742 kilometers.**

In [5]:
planet = "Earth"
diameter = 12742


In [6]:
print("The diameter of {} is {} kilometers.".format(planet, diameter))


The diameter of Earth is 12742 kilometers.


**3. In this nest dictionary grab the word "hello"**

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [8]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


**Numpy**

In [9]:
import numpy as np

**4.1 Create an array of 10 zeros?**

**4.2 Create an array of 10 fives?**

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**5. Create an array of all even integers from 20 to 35**

In [14]:
np.arange(20,35,2)

array([20, 22, 24, 26, 28, 30, 32, 34])

**6. Create 3x3 matrix with values ranging from 0 to 8**

In [15]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**7. Concatenate a and b**

In [16]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [17]:
np.concatenate((a,b), axis=0, out=None)

array([1, 2, 3, 4, 5, 6])

**Pandas**

**8. Create a dataframe with 3 rows and 2 columns**

In [18]:
import pandas as pd
df = pd.DataFrame(index=np.arange(3), columns=np.arange(2))

In [19]:
print(df)

     0    1
0  NaN  NaN
1  NaN  NaN
2  NaN  NaN


In [20]:
df.shape

(3, 2)

**9.Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023**

In [21]:
date = pd.date_range("01-01-2023", "11-02-2023")
print(date)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-10-24', '2023-10-25', '2023-10-26', '2023-10-27',
               '2023-10-28', '2023-10-29', '2023-10-30', '2023-10-31',
               '2023-11-01', '2023-11-02'],
              dtype='datetime64[ns]', length=306, freq='D')


**10. Create 2D list to DataFrame**

In [23]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [24]:
data = pd.DataFrame.from_records(lists)
print(data)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
